### ISSUE TITLE
Create the 'master' branch.

### ISSUE THREAD

**Issue by ob1dev** [SitecoreSupport/Sitecore.Support.125233#1]
Please create the `master` branch. It must follow [this](https://github.com/SitecoreSupport/Readme/blob/26f12493ebffea18f6728b3f296b2451c74438a7/template/master/readme.md) template.

**Comment by SC-ILI** [comment]
It looks like there was some error in the patch creator, usually this branch is created automatically. 
I have created the master branch manually according to the provided template.

**Comment by ob1dev** [comment]
Thanks!
